version: "3"

vars:
  PROJECT_CODE: ePrometna_Server

  # folders
  BIN_FOLDER: bin
  TEST_PCKGS: ./util/* ./controller ./service ./dto

  # build options
  # -v  print the names of packages as they are compiled
  # -s  omit the symbol table and debug information
  # -w  omit the DWARF symbol table
  #
  BUILD_OPTIONS: -v -ldflags="-s -w "

includes:
  osbuild:
    taskfile: taskfile_{{OS}}.yaml
    flatten: true

tasks:
  default:
    cmds:
      - task: list-tools
    silent: false

  rebuild:
    deps: [clean-db, clean-modcache, clean-cache]
    cmds:
      - task: tidy
      - task: verify
      - task: build
        vars: { TASK_OPTIONS: "-a" }
    silent: false

  clean-modcache:
    cmd: go clean --modcache

  clean-cache:
    cmd: go clean -cache

  verify:
    cmds:
      - go mod verify
      - go vet ./...

  update:
    cmds:
      - go get -u all

  dev:
    deps: [generate-swagger, start-db]
    cmds:
      - defer: { task: stop-db }
      - cmd: air

  test:
    cmd: go test -v {{.TEST_PCKGS}}

  coverage:
    cmds:
      - cmd: go test {{.TEST_PCKGS}} -coverprofile=coverage.out
      - cmd: go tool cover -html=coverage.out

  start-db:
    cmds:
      - cmd: docker-compose up -d

  stop-db:
    cmd: docker-compose stop

  clean-db:
    cmd: docker-compose down -v

  generate-swagger:
    internal: true
    cmds:
      - cmd: swag fmt
      - cmd: swag init
      # - cmd: swag-v2 init --v3.1 --outputTypes yaml
    ignore_error: true

  list:
    cmds:
      - go list -u -m all

  list-tools:
    cmds:
      - go version
      - gcc --version
      - task --version
    silent: true
