definitions:
  dto.LoginDto:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  dto.NewUserDto:
    properties:
      birthDate:
        type: string
      email:
        type: string
      firstName:
        maxLength: 100
        minLength: 2
        type: string
      lastName:
        maxLength: 100
        minLength: 2
        type: string
      oib:
        type: string
      password:
        minLength: 6
        type: string
      residence:
        maxLength: 255
        type: string
      role:
        enum:
        - hak
        - mupadmin
        - osoba
        - firma
        - policija
        - superadmin
        type: string
      uuid:
        type: string
    required:
    - birthDate
    - email
    - firstName
    - lastName
    - oib
    - password
    - residence
    - role
    type: object
  dto.NewVehicleDto:
    properties:
      additionalTireSizes:
        description: Dodatne dimenzije guma // (15)
        type: string
      bodyShape:
        description: Oblik karoserije // (2)
        type: string
      chassisNumber:
        description: Broj šasije // E
        type: string
      co2Emissions:
        description: Emisija CO2 // V7
        type: string
      colourOfVehicle:
        description: Boja vozila // R
        type: string
      dateFirstRegistration:
        description: Datum prve registracije // B
        type: string
      ecCategory:
        description: EC kategorija // V9
        type: string
      engineCapacity:
        description: Obujam motora // P1
        type: string
      enginePower:
        description: Snaga motora // P2
        type: string
      engineSpeedForStationaryNoiseTest:
        description: Broj okretaja motora pri ispitivanju buke u stacionarnom stanju
          // U2
        type: string
      firstRegistrationInCroatia:
        description: Prva registracija u Hrvatskoj // (4)
        type: string
      fuelOrPowerSource:
        description: Gorivo ili izvor energije // P3
        type: string
      height:
        description: Visina // (8)
        type: string
      homologationType:
        description: Homologacijski tip // D2
        type: string
      length:
        description: Dužina // (6)
        type: string
      mark:
        description: Marka // D1
        type: string
      maximumNetPower:
        description: Najveća neto snaga // T
        type: string
      mb:
        description: 'MB (pretpostavka: proizvođač) // (13)'
        type: string
      model:
        description: Model // (14)
        type: string
      numberOfAxles:
        description: Broj osovina // L
        type: string
      numberOfDrivenAxles:
        description: Broj pogonskih osovina // (9)
        type: string
      numberOfSeats:
        description: Broj sjedala // S1
        type: string
      ownerUuid:
        type: string
      permissibleMaximumLadenMass:
        description: Dopuštena najveća masa // F2
        type: string
      permissiblePayload:
        description: Dopuštena nosivost // (5)
        type: string
      ratedEngineSpeed:
        description: Nazivni broj okretaja motora // P4
        type: string
      registration:
        type: string
      stationaryNoiseLevel:
        description: Razina buke u stacionarnom stanju // U1
        type: string
      technicallyPermissibleMaximumLadenMass:
        description: Tehnički dopuštena najveća masa // F1
        type: string
      tireSize:
        description: Dimenzije guma // (11)
        type: string
      tradeName:
        description: Trgovački naziv // D3
        type: string
      traveledDistance:
        type: integer
      typeApprovalNumber:
        description: Broj homologacije // K
        type: string
      uniqueModelCode:
        description: Jedinstvena oznaka modela // (12)
        type: string
      unladenMass:
        description: Masa praznog vozila // G
        type: string
      vehicleCategory:
        description: Kategorija vozila // J
        type: string
      vehicleType:
        description: Tip vozila (16) // (16)
        type: string
      vehicleUse:
        description: Namjena vozila // (3)
        type: string
      width:
        description: Širina // (7)
        type: string
    type: object
  dto.TokenDto:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  dto.UserDto:
    properties:
      birthDate:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      oib:
        type: string
      residence:
        type: string
      role:
        type: string
      uuid:
        type: string
    type: object
  dto.VehicleDetailsDto:
    properties:
      additionalTireSizes:
        description: Dodatne dimenzije guma // (15)
        type: string
      bodyShape:
        description: Oblik karoserije // (2)
        type: string
      chassisNumber:
        description: Broj šasije // E
        type: string
      co2Emissions:
        description: Emisija CO2 // V7
        type: string
      colourOfVehicle:
        description: Boja vozila // R
        type: string
      dateFirstRegistration:
        description: Datum prve registracije // B
        type: string
      drivers:
        items:
          $ref: '#/definitions/dto.UserDto'
        type: array
      ecCategory:
        description: EC kategorija // V9
        type: string
      engineCapacity:
        description: Obujam motora // P1
        type: string
      enginePower:
        description: Snaga motora // P2
        type: string
      engineSpeedForStationaryNoiseTest:
        description: Broj okretaja motora pri ispitivanju buke u stacionarnom stanju
          // U2
        type: string
      firstRegistrationInCroatia:
        description: Prva registracija u Hrvatskoj // (4)
        type: string
      fuelOrPowerSource:
        description: Gorivo ili izvor energije // P3
        type: string
      height:
        description: Visina // (8)
        type: string
      homologationType:
        description: Homologacijski tip // D2
        type: string
      length:
        description: Dužina // (6)
        type: string
      mark:
        description: Marka // D1
        type: string
      maximumNetPower:
        description: Najveća neto snaga // T
        type: string
      mb:
        description: 'MB (pretpostavka: proizvođač) // (13)'
        type: string
      model:
        description: Model // (14)
        type: string
      numberOfAxles:
        description: Broj osovina // L
        type: string
      numberOfDrivenAxles:
        description: Broj pogonskih osovina // (9)
        type: string
      numberOfSeats:
        description: Broj sjedala // S1
        type: string
      owner:
        $ref: '#/definitions/dto.UserDto'
      pastOwners:
        items:
          $ref: '#/definitions/dto.UserDto'
        type: array
      permissibleMaximumLadenMass:
        description: Dopuštena najveća masa // F2
        type: string
      permissiblePayload:
        description: Dopuštena nosivost // (5)
        type: string
      productionYear:
        type: integer
      ratedEngineSpeed:
        description: Nazivni broj okretaja motora // P4
        type: string
      registration:
        type: string
      stationaryNoiseLevel:
        description: Razina buke u stacionarnom stanju // U1
        type: string
      technicallyPermissibleMaximumLadenMass:
        description: Tehnički dopuštena najveća masa // F1
        type: string
      tireSize:
        description: Dimenzije guma // (11)
        type: string
      tradeName:
        description: Trgovački naziv // D3
        type: string
      typeApprovalNumber:
        description: Broj homologacije // K
        type: string
      uniqueModelCode:
        description: Jedinstvena oznaka modela // (12)
        type: string
      unladenMass:
        description: Masa praznog vozila // G
        type: string
      uuid:
        type: string
      vehicleCategory:
        description: Kategorija vozila // J
        type: string
      vehicleType:
        description: Tip vozila (16) // (16)
        type: string
      vehicleUse:
        description: Namjena vozila // (3)
        type: string
      width:
        description: Širina // (7)
        type: string
    type: object
  dto.VehicleDto:
    properties:
      allowedTo:
        description: 'NOTE: can be date or empty if empty then it is allowed forever'
        type: string
      registration:
        type: string
      uuid:
        type: string
      vehicleModel:
        type: string
      vehicleType:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns access and refresh tokens
      parameters:
      - description: Login credentials
        in: body
        name: loginDto
        required: true
        schema:
          $ref: '#/definitions/dto.LoginDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TokenDto'
      summary: User login
      tags:
      - auth
  /auth/refresh:
    post:
      description: Generates a new access token using a valid refresh token
      parameters:
      - description: Refresh Token
        in: body
        name: refreshToken
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TokenDto'
      summary: Refresh Access Token
      tags:
      - auth
  /user:
    post:
      parameters:
      - description: Data for new user
        in: body
        name: model
        required: true
        schema:
          $ref: '#/definitions/dto.NewUserDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.UserDto'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Create new user
      tags:
      - user
  /user/{uuid}:
    delete:
      description: delete a user with uuid
      parameters:
      - description: user uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: delete user with uuid
      tags:
      - user
    get:
      description: get a user with uuid
      parameters:
      - description: user uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserDto'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: get user with uuid
      tags:
      - user
    put:
      parameters:
      - description: uuid of user to be updated
        in: path
        name: uuid
        required: true
        type: string
      - description: Data for updating user
        in: body
        name: model
        required: true
        schema:
          $ref: '#/definitions/dto.UserDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserDto'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Update user with new dat
      tags:
      - user
  /user/all-users:
    get:
      description: Fetches all users for superadmin
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.UserDto'
            type: array
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: Get all users for superadmin
      tags:
      - user
  /user/my-data:
    get:
      description: Fetches the currently logged-in user's data based on the JWT token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserDto'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get logged-in user data
      tags:
      - user
  /user/police-officers:
    get:
      description: Fetches all police officers for MUP Admin
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.UserDto'
            type: array
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: Get all police officers for MUP Admin
      tags:
      - user
  /user/search:
    get:
      description: Performs a fuzzy search for users by first name, last name, or
        full name with similarity matching
      parameters:
      - description: Search query
        in: query
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.UserDto'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Search users by name
      tags:
      - user
  /vehicle:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.VehicleDto'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Gets your vehicles
      tags:
      - vehicle
    post:
      description: Create new vehicle with an owner
      parameters:
      - description: Vehicle model
        in: body
        name: model
        required: true
        schema:
          $ref: '#/definitions/dto.NewVehicleDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.VehicleDto'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Creates new vehicle
      tags:
      - vehicle
  /vehicle/{uuid}:
    delete:
      description: Preforms a soft delete
      parameters:
      - description: Vehicle UUID
        in: path
        name: uuid
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Soft delete on vehicle
      tags:
      - vehicle
    get:
      parameters:
      - description: Vehicle UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.VehicleDetailsDto'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Gets a vehicle with uuid
      tags:
      - vehicle
swagger: "2.0"
