definitions:
  dto.LoginDto:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.TmodelDto:
    properties:
      age:
        type: integer
      name:
        type: string
      uuid:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns access and refresh tokens
      parameters:
      - description: Login credentials
        in: body
        name: loginDto
        required: true
        schema:
          $ref: '#/definitions/dto.LoginDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: User login
      tags:
      - login
  /refresh:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Generates a new access token using a valid refresh token
      parameters:
      - description: Refresh Token
        in: formData
        name: refresh_token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: access_token
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Refresh Access Token
      tags:
      - auth
  /test:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: ping example
      tags:
      - test
    post:
      consumes:
      - application/json
      description: Create a test model
      parameters:
      - description: Test model
        in: body
        name: model
        required: true
        schema:
          $ref: '#/definitions/dto.TmodelDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Creates test item
      tags:
      - test
    put:
      consumes:
      - application/json
      description: do a insert into databse with test user and returns inserted struct
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Insert new test struct
      tags:
      - test
  /test/{uuid}:
    delete:
      consumes:
      - application/json
      description: Deletes an item with uuid
      parameters:
      - description: Test model UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Deletes test item
      tags:
      - test
swagger: "2.0"
