info:
  contact: {}
paths:
  /test/:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: ping example
      tags:
      - test
    post:
      consumes:
      - application/json
      description: do a insert into databse with test user and returns inserted struct
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Insert new test struct
      tags:
      - test
  /test/{uuid}:
    delete:
      consumes:
      - application/json
      description: do a delete on item uui
      parameters:
      - description: Test model UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delets test item
      tags:
      - test
swagger: "2.0"
